# Generated by Django 3.1.7 on 2021-04-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20210414_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviewed_post',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
