# Generated by Django 3.1.7 on 2021-07-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_form'),
        ('dashboard', '0002_auto_20210722_1751'),
        ('dashboard', '0002_auto_20210722_1802'),
    ]

    operations = [
    ]
